# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afb0c673b57300204ddf85f93017121222a5e4957a2a4845fc78829b03d0f7924fa2fe43046841ac6ce9224552f064c3ff6b33ad9b9b39b8959adf956d2af17b

test:
  secret_key_base: dff1bd9a3b26044706da2dea0cef1284f8f1d0d3c90b3f92e963a8fa3721e4e7a5cd7f49547fd2f6bd214acf2b25ea0326b11b28fd231bae9a10e0547d312d3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
